### ISSUE TITLE
Higher Accuracy on CIFAR100 Than Reported: Possible Configuration Error?

### ISSUE THREAD

**Issue by sehyun03** [njustkmg/PAL#1]
Thank you very much for sharing your code.

On CIFAR100, I got the following result which shows a bit higher accuracy than the paper.

<img width="725" alt="image" src="https://github.com/njustkmg/NeurIPS2023-PAL/assets/23238163/6e3bc6d9-7660-4ebf-80ac-6790c0d95a17">

I guess that I used some kind of wrong configurations.

I used following command for running the CIFAR100 experiment.

>### 20% ID classes (20 ID classes)
> python3 main.py \
> --save_dir checkpoint/PAL_Cifar100_ID20_28/seed1 \
> --out checkpoint/PAL_Cifar100_ID20_28/seed1 \
> --gpu-id 0 \
> --num_classes 20 \
> --need-ID 1450 \
> --num-labeled 50 \
> --query-batch 1500 \
> --miu 0.8 \
> --max-query 10 \
> --dataset cifar100 \
> --eval-step 70 \
> --epochs 100 \
> --arch wideresnet \
> --lambda_oem 0.1 \
> --lambda_socr 0.5 \
> --query-strategy PAL \
> --batch-size 128 \
> --lr 0.01 \
> --expand-labels \
> --seed 1 \
> --mu 2

Could you **check and share your configuration for running the CIFAR100 experiment**?

**Comment by njustkmg** [comment]
Thank you for your question. For the CIFAR-100 dataset, to maintain consistency with the existing methods, we set the --eval-step to 60. Based on your results, the difference may also be due to variations in the machine hardware.
